version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: backend_vending_machine_db
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./dbdata/:/var/lib/postgresql/data
    networks:
      - maze

volumes:
  dbdata:

networks:
  maze:
