default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :development, :database) %>
  host: <%= Rails.application.credentials.dig(:db, :development, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :development, :port) %>
  username: <%= Rails.application.credentials.dig(:db, :development, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :development, :password) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :test, :database) %>
  host: <%= Rails.application.credentials.dig(:db, :test, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :test, :port) %>
  username: <%= Rails.application.credentials.dig(:db, :test, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :test, :password) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :production, :database) %>
  host: <%= Rails.application.credentials.dig(:db, :production, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :production, :port) %>
  username: <%= Rails.application.credentials.dig(:db, :production, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :production, :password) %>
